apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "chathurangadinusha90@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "uins jwwt zzzk gyem"
type: Opaque

# Passw0rd@1234